In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('/content/DFORE82sprdsht.csv')

In [8]:
amts= ['amt_fw2_weeks',	'amt_fw4_weeks',	'amt_bc2_weeks',	'amt_bc4_weeks'	]

In [13]:
for a in amts:
  df['act_'+a[4:]]= 'False'
  df['act_'+a[4:]]= (df[a]!=0)

In [14]:
df.head()

   client_account_id  user_id  ... act_bc2_weeks  act_bc4_weeks
0            4257171    24290  ...          True           True
1            2101691    33595  ...          True           True
2            4214530   996376  ...          True           True
3            5100087   276077  ...          True           True
4             201801   769939  ...          True           True

[5 rows x 15 columns]

In [17]:
amt_sum= {'amt_fw2_weeks':'sum',	'amt_fw4_weeks': 'sum',	'amt_bc2_weeks': 'sum',	
          'amt_bc4_weeks': 'sum','act_fw2_weeks':'sum',	'act_fw4_weeks':'sum', 'act_bc2_weeks': 'sum',	'act_bc4_weeks': 'sum',
          'vnd_fw2_weeks': 'sum', 'vnd_fw4_weeks': 'sum',	'vnd_bc2_weeks': 'sum',	'vnd_bc4_weeks': 'sum'}

In [18]:
df.loc[df.eventName!='emailBounce'].groupby('eventName').agg(amt_sum)

            amt_fw2_weeks  amt_fw4_weeks  ...  vnd_bc2_weeks  vnd_bc4_weeks
eventName                                 ...
emailClick        2205920        4377952  ...          15776          32007
emailOpen        67050013      131316417  ...         472347         967084
emailSend       143944456      282628198  ...        1041689        2147460

[3 rows x 12 columns]