In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df= pd.read_csv('/DFORE339data.csv', low_memory=True)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [22]:
df.columns

Index(['Unnamed: 0', 'Reporting_level', 'vendor', 'as400id', 'location_id',
       'Location_Name', 'Branch_Id', 'Branch_Name', 'state', 'room_id',
       'machine_type', 'TimeSinceFirstVend', 'TimeSinceLastTxn', 'Tenure_Flag',
       'Txn_Avg_Machine_Cnt', 'Room_Open_Hours', 'Daily_Max_Room_Vend_Hours',
       'Base_Vends', 'Base_Vend_Amount', 'Top_Up_Vends', 'Top_Up_Vend_Amount',
       'Total_Vend_Hours', 'Total_Hours_Open', 'Overall_Utilization',
       'Max_Daily_Vends', 'Daily_Peak_Utilization',
       'Full_Room_Util_Gross_Hours', 'Full_Room_Util_Vend_PCT',
       'Full_Room_Util_Total_PCT', 'Avg_Daily_Vends', 'VDPM', 'Vend_Price',
       'AvgUtil_M', 'AvgUtil_T', 'AvgUtil_W', 'AvgUtil_Th', 'AvgUtil_F',
       'AvgUtil_Sa', 'AvgUtil_Su', 'nrpm', 'ContractExpirationDate',
       'Days_To_ContractExpiration', 'UtilTimeFrame', 'UtilTimeFrame_bkt',
       'machine_bkt', 'overall_util_bkt', 'peak_util_bkt', 'VDPM_bkt',
       'nrpm_bkt', 'score', 'Overall_Utilization_median',
       'Daily_Peak_Utilization_q90'],
      dtype='object')

In [23]:
df.groupby(['score', 'vendor', 'machine_type']).agg({'room_id':'nunique', 'Txn_Avg_Machine_Cnt': 'sum'}).sort_index(ascending= False)

                           room_id  Txn_Avg_Machine_Cnt
score vendor machine_type
1111  DI     WASHER          12334                35055
             STACKED            68                  177
             DRYER           12044                32957
      CSCGo  WASHER           5751                14961
             STACKED            16                   34
...                            ...                  ...
100   DI     WASHER             34                   34
             STACKED             4                    4
             DRYER              33                   33
      CSCGo  WASHER             43                   43
             DRYER              49                   49

[65 rows x 2 columns]

In [24]:
df.groupby('score').agg({'Txn_Avg_Machine_Cnt': 'sum'}).sort_index(ascending= False)

       Txn_Avg_Machine_Cnt
score
1111                 97214
1110                 57925
1101                 22927
1100                  7126
1011                 19161
1010                 14125
1001                  1004
1000                   431
111                   3570
110                   1959
101                    799
100                    163

In [25]:
df.columns

Index(['Unnamed: 0', 'Reporting_level', 'vendor', 'as400id', 'location_id',
       'Location_Name', 'Branch_Id', 'Branch_Name', 'state', 'room_id',
       'machine_type', 'TimeSinceFirstVend', 'TimeSinceLastTxn', 'Tenure_Flag',
       'Txn_Avg_Machine_Cnt', 'Room_Open_Hours', 'Daily_Max_Room_Vend_Hours',
       'Base_Vends', 'Base_Vend_Amount', 'Top_Up_Vends', 'Top_Up_Vend_Amount',
       'Total_Vend_Hours', 'Total_Hours_Open', 'Overall_Utilization',
       'Max_Daily_Vends', 'Daily_Peak_Utilization',
       'Full_Room_Util_Gross_Hours', 'Full_Room_Util_Vend_PCT',
       'Full_Room_Util_Total_PCT', 'Avg_Daily_Vends', 'VDPM', 'Vend_Price',
       'AvgUtil_M', 'AvgUtil_T', 'AvgUtil_W', 'AvgUtil_Th', 'AvgUtil_F',
       'AvgUtil_Sa', 'AvgUtil_Su', 'nrpm', 'ContractExpirationDate',
       'Days_To_ContractExpiration', 'UtilTimeFrame', 'UtilTimeFrame_bkt',
       'machine_bkt', 'overall_util_bkt', 'peak_util_bkt', 'VDPM_bkt',
       'nrpm_bkt', 'score', 'Overall_Utilization_median',
       'Daily_Peak_Utilization_q90'],
      dtype='object')

In [26]:
df['Hygiene_Machine_num']=1

In [33]:
df['OverUtil_cnt']= np.where(df.score==1111, df.Overall_Utilization.divide(df.Overall_Utilization_median), 1)

In [35]:
df.loc[df.score==1111, ['Overall_Utilization', 'Overall_Utilization_median']].head(5)

   Overall_Utilization  Overall_Utilization_median
2                 5.67                         5.7
3                19.94                         5.7
5                 5.74                         5.7
8                 1.80                         5.7
9                 2.99                         5.7