In [110]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
lnk= '/content/Price_increment_results_0512.xlsx'

In [112]:
dfs=[]
for sheet in ['control', 'test1', 'test2']:
  df= pd.read_excel(lnk, sheet_name= sheet)
  df['cohort']= sheet
  dfs.append(df)

In [113]:
cutoffs={1: [.01,.99],
         2: [.05, .95],
         3: [.1,.9]}

In [114]:
# df= pd.concat(dfs, axis=0)

In [115]:
# cutoff= df.loc[:, ['Days Diff.', 'Machine Diff.']].abs().describe(percentiles=[.75, .9,.95,.99, .999]).loc['90%'].to_dict()

In [140]:
met_dict= {'as400id': 'nunique', 'total_transacted_days_pre': 'sum', 'machine_cnt_pre': 'sum',
       'total_vends_pre': 'sum', 'total_amount_pre': 'sum', 'Days Diff.': 'sum', 'Machine Diff.': 'sum',
       'Vends Diff.': 'sum', 'Amount Diff.': 'sum',  'total_transacted_days_post': 'sum',
       'machine_cnt_post': 'sum', 'total_vends_post': 'sum', 'total_amount_post': 'sum', 'DDCut': 'min', 'MDCut': 'max'}

In [153]:
aggs=[]
for t in [.96, .95, .92, .9]:
  df= pd.concat(dfs, axis=0)
  # df['McDayDiff']= df['Days Diff.'].abs()*df['Machine Diff.'].abs()
  dq= df.groupby('cohort')['Days Diff.', 'Machine Diff.'].agg(lambda x: x.abs().quantile(t)).rename(columns={'Days Diff.': 'DDCut','Machine Diff.': 'MDCut' })
  df= df.merge(dq, left_on='cohort', right_on='cohort')
  df1= df.loc[(df['Days Diff.'].abs() <= df.DDCut) & (df['Machine Diff.'].abs() <= df.MDCut)]
  df2= df1.groupby('cohort').agg(met_dict).reset_index()
  df2['CutOffPercentile']= t
  # df2['HighCutOff']= v[1]
  aggs.append(df2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """

In [154]:
pd.concat(aggs, axis=0).T

,0,1,2,0,1,2,0,1,2,0,1,2
cohort,control,test1,test2,control,test1,test2,control,test1,test2,control,test1,test2
as400id,39,74,76,38,74,76,37,68,72,36,64,67
total_transacted_days_pre,903,1716,1761,878,1716,1761,851,1645,1725,837,1623,1637
machine_cnt_pre,442,787,819,428,787,819,410,743,792,392,726,752
total_vends_pre,14181,29471,30402,13869,29471,30402,13488,28550,30279,13297,28471,29671
total_amount_pre,24005.6,53187.7,56151.99,23464.3,53187.7,56151.99,22809.05,51662.65,55928.49,22468.55,51518.4,54831.49
Days Diff.,31,18,25,42,18,25,40,-2,29,30,-12,-1
Machine Diff.,-10,-8,-2,-10,-8,-2,-16,-9,-10,-15,-5,-13
Vends Diff.,-282,1342,321,-113,1342,321,-128,965,298,-247,930,8
Amount Diff.,-435.35,3406.29,4724.62,-137.95,3406.29,4724.62,-147.45,2655.94,4652.47,-360.7,2570.19,4010.27
total_transacted_days_post,934,1734,1786,920,1734,1786,891,1643,1754,867,1611,1636
machine_cnt_post,432,779,817,418,779,817,394,734,782,377,721,739
total_vends_post,13899,30813,30723,13756,30813,30723,13360,29515,30577,13050,29401,29679
total_amount_post,23570.25,56593.99,60876.61,23326.35,56593.99,60876.61,22661.6,54318.59,60580.96,22107.85,54088.59,58841.76
DDCut,11.64,10.0,6.0,10.9,10.0,6.0,10.0,8.76,6.0,9.8,7.2,5.0
MDCut,8.88,4.0,4.0,6.0,4.0,4.0,4.92,3.0,3.0,3.0,2.2,3.0
CutOffPercentile,0.96,0.96,0.96,0.95,0.95,0.95,0.92,0.92,0.92,0.9,0.9,0.9

In [126]:
df['Days Diff.'].abs() <= df.DDCut

0      False
1       True
2       True
3       True
4       True
       ...
198     True
199     True
200     True
201    False
202     True
Length: 203, dtype: bool

In [30]:
met_dict= {'as400id': 'nunique', 'total_transacted_days_pre': 'sum', 'machine_cnt_pre': 'sum',
       'total_vends_pre': 'sum', 'total_amount_pre': 'sum', 'Days Diff.': 'sum', 'Machine Diff.': 'sum',
       'Vends Diff.': 'sum', 'Amount Diff.': 'sum',  'total_transacted_days_post': 'sum',
       'machine_cnt_post': 'sum', 'total_vends_post': 'sum', 'total_amount_post': 'sum',
       'McDayDiff': ['min', 'max'], 'qlow': 'min', 'qHi': 'max'}

In [31]:
aggs=[]
for i,v in cutoffs.items():
  df= pd.concat(dfs, axis=0)
  df['McDayDiff']= df['Days Diff.']*df['Machine Diff.']
  dq= df.groupby('cohort')['McDayDiff'].agg([('qlow', lambda x: x.quantile(v[0])), ('qHi', lambda x: x.quantile(v[1]))]).reset_index()
  df= df.merge(dq, left_on='cohort', right_on='cohort')
  df1= df.loc[df.McDayDiff.between(df.qlow, df.qHi)]
  df2= df1.groupby('cohort').agg(met_dict).reset_index()
  df2['LowCutOff']=v[0]
  df2['HighCutOff']= v[1]
  aggs.append(df2)

In [32]:
pd.concat(aggs, axis=0).T

                                           0         1         2         0  \
cohort                               control     test1     test2   control
as400id                    nunique        41        77        79        37
total_transacted_days_pre  sum           928      1758      1816       886
machine_cnt_pre            sum           455       808       857       432
total_vends_pre            sum         14847     30019     31372     14698
total_amount_pre           sum       25373.9   54247.7  58030.49  25125.85
Days Diff.                 sum            22        17        15         3
Machine Diff.              sum           -18        11       -11        -7
Vends Diff.                sum          -701      1537       544      -854
Amount Diff.               sum      -1094.65   3771.89   5382.22  -1461.85
total_transacted_days_post sum           950      1775      1831       889
machine_cnt_post           sum           437       819       846       425
total_vends_post           sum         14146     31556     31916     13844
total_amount_post          sum      24279.25  58019.59  63412.71   23664.0
McDayDiff                  min            -3        -2       -16        -1
                           max           150        63        15        12
qlow                       min         -7.06     -3.32     -16.8      -1.9
qHi                        max        172.62     64.54      15.6     130.8
LowCutOff                               0.01      0.01      0.01      0.05
HighCutOff                              0.99      0.99      0.99      0.95

                                           1         2         0         1  \
cohort                                 test1     test2   control     test1
as400id                    nunique        72        74        34        68
total_transacted_days_pre  sum          1686      1736       826      1652
machine_cnt_pre            sum           782       803       395       757
total_vends_pre            sum         29102     30350     13893     28927
total_amount_pre           sum      52303.45  56089.54  23723.35   52007.7
Days Diff.                 sum            17         2         3        19
Machine Diff.              sum            -2       -17        -9         4
Vends Diff.                sum          1559       183      -838      1509
Amount Diff.               sum       3779.54   4455.12  -1425.85   3579.84
total_transacted_days_post sum          1703      1738       829      1671
machine_cnt_post           sum           780       786       386       761
total_vends_post           sum         30661     30533     13055     30436
total_amount_post          sum      56082.99  60544.66   22297.5  55587.54
McDayDiff                  min             0        -2         0         0
                           max            10         9         6         6
qlow                       min           0.0      -2.0       0.0       0.0
qHi                        max          10.1       9.0       8.4       6.4
LowCutOff                               0.05      0.05       0.1       0.1
HighCutOff                              0.95      0.95       0.9       0.9

                                           2
cohort                                 test2
as400id                    nunique        65
total_transacted_days_pre  sum          1591
machine_cnt_pre            sum           733
total_vends_pre            sum         28625
total_amount_pre           sum      53112.19
Days Diff.                 sum             9
Machine Diff.              sum           -10
Vends Diff.                sum           454
Amount Diff.               sum       4699.87
total_transacted_days_post sum          1600
machine_cnt_post           sum           723
total_vends_post           sum         29079
total_amount_post          sum      57812.06
McDayDiff                  min             0
                           max             1
qlow                       min           0.0
qHi                        max           1.0
LowCutOff                                0.1
HighCutOff                               0.9